const dotenv=require('dotenv');
dotenv.config();
module.exports={
PORT:process.env.PORT,
DB_URL:process.env.DB_URL,
JWT_SECRET:process.env.JWT_SECRET,
JWT_EXPIN:process.env.JWT_EXPIRES,


CLOUDINARY_API_KEY:process.env.CLOUDINARY_API_KEY,
CLOUDINARY_API_SECRET:process.env.CLOUDINARY_API_SECRET,
CLOUDINARY_CLOUDE_NAME:process.env.CLOUDINARY_CLOUDE_NAME,
FRONTEND_URL:process.env.FRONTEND_URL,
COOKIE_SECURE:process.env.COOKIE_SECURE,

GOOGLE_PROJECT_ID:process.env.GOOGLE_PROJECT_ID,
GOOGLE_PRIVATE_KEY_ID:process.env.GOOGLE_PRIVATE_KEY_ID,
GOOGLE_PRIVATE_KEY:process.env.GOOGLE_PRIVATE_KEY,
GOOGLE_CILNT_EMAIL:process.env.GOOGLE_CILNT_EMAIL,
GOOGLE_CLINT_ID:process.env.GOOGLE_CLINT_ID,
}
